#+TITLE: jest.el
[[https://melpa.org/#/jest][file:https://melpa.org/packages/jest-badge.svg]]

Credit: [[https://github.com/wbolster/emacs-python-pytest][emacs-python-pytest]]

This package provides helpers to run jest.

* Installation
~jest.el~ is available from melpa.

With ~use-package~:
#+BEGIN_SRC elisp
(use-package jest)
#+END_SRC
Manually:
#+BEGIN_SRC
M-x package-install RET jest RET
#+END_SRC
* Overview
The main command is jest-popup, which will show a
dispatcher menu, making it easy to change various options and
switches, and then run jest using one of the actions.
- jest (run all tests)
- jest-file (current file)
- jest-file-dwim (‘Do what I mean’ for current file)
- jest-function (current function)
- jest-function-dwim (‘Do what I mean’ for current function)
- jest-last-failed (rerun previous failures)
- jest-repeat (repeat last invocation)

A prefix argument causes the generated command line to be offered
for editing, and various customization options influence how some
of the commands work. See the README.org for detailed information.

* Jest Popup
#+BEGIN_SRC
Switches
 -b bail (--bail)
 -c colors (--colors)
 -C coverage (--coverage)
 -d run doctests (--doctest-modules)
 -D debug jest config (--debug)
 -e expand (--expand)
 -f force exit (--forceExit)
 -l last commit (--lastCommit)
 -o only changed (--onlyChanged)
 -s silent (--silent)
 -v verbose (--verbose)
 -w watch (--watch)
 -W watch all (--watchAll)

Options
 =c config file (--config=)
 =k only names matching expression (-t)
 =o output file (--outputFile=)
 =x exit after N failures or errors (--maxfail=)

Run tests
 t Test all            x Test last-failed

Run tests for current context
 f Test file           F Test this file
 d Test def/class      D This def/class

Repeat tests
 r Repeat last test run
#+END_SRC
* Contributing
Please create a [[https://github.com/Emiller88/emacs-jest/issues/new][new issue]] or [[https://github.com/Emiller88/emacs-jest/compare][submit a PR]].
